---
- hosts: all
  vars_files:
    - vars.yml

  tasks:
  - name: Create a directory for django apps.
    file: state=directory path={{apps_root}}

  - name: Create a virtualenv directory in django apps directory.
    file: state=directory path={{apps_root}}/env/

  - name: Install required system packages.
    apt: pkg={{item}} state=installed update-cache=yes
    with_items: system_packages

  - name: Install pip and virtualenv
    easy_install: name={{item}}
    with_items: easy_install_packages

  - name: Install Python Packages - django and gunicorn
    pip: name={{item}} virtualenv={{apps_root}}/env/
    with_items: python_packages

  - name: start django project if it doesn't exist
    shell: "{{apps_root}}/env/bin/django-admin.py startproject {{project_name}} chdir={{apps_root}} creates={{apps_root}}/{{project_name}}"

  - name: copy nginx configuration file and start nginx as a service.
    copy: src=conf/nginx.conf dest=/etc/nginx/sites-enabled/
    notify: restart nginx

  - name: copy gunicorn_init script
    copy: src=conf/gunicorn_init.conf dest=/etc/init

  - name: set gunicorn_init as a service and start
    file: src=/etc/init/gunicorn_init.conf dest=/etc/init.d/gunicorn_init owner=root group=root state=link
    notify: restart gunicorn

  handlers:
    - include: handlers.yml