---
- hosts: all
  vars_files:
    - vars.yml

  tasks:
  - name: Create a directory for django apps.
    file: state=directory path={{apps_root}}

  - name: Create a virtualenv directory in django apps directory.
    file: state=directory path={{apps_root}}/env/

  - name: Install required system packages.
    apt: pkg={{item}} state=installed update-cache=yes
    with_items: system_packages

  - name: Install pip and virtualenv
    easy_install: name={{item}}
    with_items: easy_install_packages

  - name: Install Python Packages - django and gunicorn
    pip: name={{item}} virtualenv={{apps_root}}/env/
    with_items: python_packages

  - name: Start django project
    shell: "{{apps_root}}/env/bin/django-admin.py startproject {{project_name}} chdir={{apps_root}} creates={{apps_root}}/{{project_name}}"

  - name: Start django app 
    shell: "{{apps_root}}/env/bin/django-admin.py startapp {{app_name}} chdir={{apps_root}}/{{project_name}} creates={{apps_root}}/{{project_name}}/{{app_name}}"

  - name: Copy settings.py to new project
    copy: src=conf/settings.py dest={{apps_root}}/{{project_name}}/{{project_name}}

  - name: setup pg_hba file
    copy: src=conf/pg_hba.conf dest=/etc/postgresql/9.1/main/pg_hba.conf owner=postgres group=postgres mode=0640
    register: pg_file

  - name: reload postgres if it changed
    service: name=postgresql state=reloaded enabled=yes
    when: pg_file.changed

  - name: Create postgreSQL database
    postgresql_db: name=mydatabase

  - name: Create postgreSQL user
    postgresql_user: db=mydatabase name=mydatabaseuser password=mypassword priv=ALL

  - name: Sync database
    django_manage: app_path={{apps_root}}/{{project_name}} command=syncdb virtualenv={{apps_root}}/env
   
  - name: Create superuser for django auth system
    shell: "{{apps_root}}/env/bin/django-admin.py createsuperuser --database mydatabase --username carlos --email cahersan@gmail.com  chdir={{apps_root}}/{{project_name}}"

  - name: Set password for django auth system
    shell: "python manage.py changepassword admin --database mydatabase  chdir={{apps_root}}/{{project_name}}"

  - name: copy nginx configuration file
    copy: src=conf/nginx.conf dest=/etc/nginx/sites-enabled/
    notify: restart nginx

  - name: copy gunicorn configuration
    copy: src=conf/gunicorn_init.conf dest=/etc/init
    notify: restart gunicorn

  handlers:
    - include: handlers.yml
