---
- hosts: all
  vars_files:
    - vars.yml

  tasks:
  - name: Create a directory for django apps.
    file: state=directory path={{apps_root}}

  - name: Create a virtualenv directory in django apps directory.
    file: state=directory path={{apps_root}}/env/

  - name: Install required system packages.
    apt: pkg={{item}} state=installed update-cache=yes
    with_items: system_packages

  - name: Install pip and virtualenv
    easy_install: name={{item}}
    with_items: easy_install_packages

  - name: Install Python Packages: django and gunicorn
    pip: name={{item}} virtualenv={{apps_root}}/env/
    with_items: python_packages

  - name: copy/start nginx configuration file.
    copy: src=conf/nginx.conf dest=/etc/nginx/sites-enabled/
    notify: restart nginx

  - name: copy/start gunicorn script
    copy: src=conf/gunicorn_init.conf dest=/etc/init
    notify: restart gunicorn

  handlers:
    - include: handlers.yml
